name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v6

      - name: Install Elm tools and cache $ELM_HOME
        uses: mpizenberg/elm-tooling-action@v1.7
        with:
          cache-key: elm-tooling.json

      - name: elm-format
        uses: sparksp/elm-format-action@v1.0.4

      - name: elm-review
        uses: sparksp/elm-review-action@v1.0.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          elm_review: ./review/elm-review.ps1
          elm_compiler: ./node_modules/.bin/elm
          elm_format: ./node_modules/.bin/elm-format

      - name: elm-verify-examples
        run: npx elm-verify-examples@5.3.0

      - name: elm-test-rs
        run: ./node_modules/.bin/elm-test-rs

      - uses: dillonkearns/elm-publish-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-elm: ./node_modules/.bin/elm
